### ISSUE TITLE
[Discussion] Board Type Field

### ISSUE THREAD

**Issue by GunHee5719** [CAUCSE/CAUSW_backend#126]
## Describe
Figma의 디자인을 보면, 게시판들을 분류해서 묶게 됩니다.
이 때 어떤 게시판들끼리 묶을 지에 대해서 하나의 field를 보유하고 있어야 할 것 같습니다.

이와 관련되어, 아이디어 제시해주세요!

**Comment by als95** [comment]
저는 저희 정해둔 기능에는 "공지", "일반" 밖에 없을 것 같다고 생각합니다.
처음은 "공지", "일반" 으로 해두고,
후에 "투표" 같은 새로운 기능이 추가 될 때마다 게시판 타입 종류를 추가해나가는 것은 어떨까요?

**Comment by GunHee5719** [comment]
좋습니다!! 그럼 그거는 백에서 static으로 전달하도록 할까요?

**Comment by GunHee5719** [comment]
아니면 프론트에서 자유롭게 확장하도록 열어둘까요?
