### ISSUE TITLE
Contributing Guide 작성

### ISSUE THREAD

**Issue by GunHee5719** [CAUCSE/CAUSW_backend#4]
`CONTRIBUTING.md` 파일 작성하기

**Comment by ase3238** [comment]
https://github.com/ase3238/CAUSW_backend/commit/b6a840026123b94f40aae1db760087bb4518ca5b

어느정도 작성 해봤는데, 괜찮으면 PR올릴게영

**Comment by ase3238** [comment]
https://github.com/CAUCSE/CAUSW_backend/pull/9
