### ISSUE TITLE
fix : userPort findByStateAndName 함수 에러 처리

### ISSUE THREAD

**Issue by realisshomyang** [CAUCSE/CAUSW_backend#529]
### 🚩 관련사항
findbystate 함수 에러 처리

### 📍 종류
- [ ] TODO (일정 정리)
- [ ] FEATURE (기능 개발)
- [x] BUG (버그)
- [ ] FAQ (질문)

### 💡 상세설명
userPort의 findByStateAndName 
<img width="967" alt="image" src="https://github.com/CAUCSE/CAUSW_backend/assets/81310047/538bfa1f-e442-4659-b581-c4b957a733cd">
이 api에서 
<img width="1439" alt="image" src="https://github.com/CAUCSE/CAUSW_backend/assets/81310047/32afa57d-dcd5-4da9-bd18-75c2ebf50835">
검색어에 아무것도 없는 상황에서 서버에서 처리하지 못한 에러가 터집니다.
<img width="670" alt="image" src="https://github.com/CAUCSE/CAUSW_backend/assets/81310047/5550da16-a351-47e5-9324-6de92cd52f4d">
그래서 검색어에 아무것도 없는 상황에서 탈퇴/추방 유저 모두를 보여주도록 로직을 변경해야할 것 같습니다. 
@pstar987 @sanggae4133

**Comment by sanggae4133** [comment]
아하.. 애매하네요 주말 중으로 처리해볼게요
