### ISSUE TITLE
refactor : RequestDto에 대해 Valid 적용

### ISSUE THREAD

**Issue by zestbear** [CAUCSE/CAUSW_backend#622]
### 🚩 관련사항

이전 작업에서 업무를 분할하지 못하여 적용하지 못한 Request Dto에 대해 Valid 적용 작업을 진행합니다.

### 📍 종류
- [ ] TODO (일정 정리)
- [x] FEATURE (기능 개발)
- [ ] BUG (버그)
- [ ] FAQ (질문)

### 💡 상세설명

Request Dto에 대해 Valid 적용합니다.

### 📃 진행사항
- [ ] todo1
- [ ] todo2

### ⚙️ 기타사항
기타 참고사항을 적어주세요.

예상 개발기간:

**Comment by sanggae4133** [comment]
<img width="1288" alt="image" src="https://github.com/user-attachments/assets/b7bcb7b2-3871-4c0d-9818-74e930baa06a">
